# Generated by Django 3.1.3 on 2020-11-20 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
                ('nationality', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='pics')),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('soundcloud', models.CharField(blank=True, max_length=100)),
                ('youtube', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True)),
                ('album_art', models.ImageField(blank=True, upload_to='album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_webapp.artist')),
            ],
        ),
    ]
